name: Daily Job

on:
 schedule:
  - cron: '0 12 * * *'   # every day at 00:00 UTC
    timezone: 'Europe/Bucharest'
 workflow_dispatch:      # optional manual trigger

env:
 #for gh
 GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
 run-job:
  runs-on: ubuntu-24.04-arm #arm for a.c actionswf logic in list/share/a
  steps:
   - uses: actions/checkout@v4
     with:
      path: games/list
   - name: Run script
     run: |
      mv games ~/
      cd ~

      git clone -n --depth=1 --filter=tree:0 https://github.com/colin-i/test
      cd test
      git sparse-checkout set stats update
      git checkout
      cd ..

      mkdir -p stats/k
      cd stats
      ~/test/stats/k2
      cd ..

      git clone -n --depth=1 --filter=tree:0 https://github.com/colin-i/actionswf
      mkdir s
      mv actionswf s/actionswf-1

      mkdir -p Desktop/actionswf
      ~/test/update/arch

      cd games
      mkdir -p swf_backup/euniverse
      cd list/share
      no_inter=x ./a

      cd ../..
      mv swf_backup/euniverse/plays.txt $GITHUB_WORKSPACE/plays.txt
   - name: test artifact
     uses: actions/upload-artifact@v4
     with:
      name: plays.txt
      path: ./plays.txt
